### ISSUE TITLE
not working with inkscape 1.1 on mac 

### ISSUE THREAD

**Issue by rmacleod96** [bferrarese/raster2laser_gcode#9]
seems to me it does not parse the  directory structure properly 

when a directory is left blank default it errors cant open file ERR02
when a directory is specified it errrors no such file/dir

a file is created in the 1st example but it is in the directory where thy .py was executed from

in the second case the file is not created 

THIS OR.  scroll down
---------------------------------------------------------------------
Traceback (most recent call last):
  File "raster2laser_gcode.py", line 546, in <module>
    _main()
  File "raster2laser_gcode.py", line 542, in _main
    e.run()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/base.py", line 141, in run
    self.save_raw(self.effect())
  File "raster2laser_gcode.py", line 143, in effect
    self.PNGtoGcode(pos_file_png_original, pos_file_png_BW, pos_file_png_GS, pos_file_gcode)
  File "raster2laser_gcode.py", line 183, in PNGtoGcode
    reader = png.Reader(pos_file_png_original)#File PNG generato
  File "/Users/RoryMacLeod/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/png.py", line 1376, in __init__
    self.file = open(kw["filename"], "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/drawing199_0001_Gray_128_-orignal.png'
------------------------------------------------------------------------

THIS      
_________________________________________________________________

Directory does not exist! Please specify existing directory!

**Comment by rmacleod96** [comment]
Never mind ,,i finally got it to work after many tries.
i tried it on another macbook ant it worked like a charm. So that left me wondering what i did wrong ..

I reinstalled inkscape and the extensions being very careful to put all the files  including the hidden ones
from raster2laser_gcode into the extensions directory. all worked ok then !

i also renamed my default directory because the origional one i used had an underscore in the dir name
and i read some of the notes in raster2laser_gcode.inx file and they mentioned that underscores messing things up
